### ISSUE TITLE
r2 and RSS for model fits

### ISSUE THREAD

**Issue by JenniGadd** [bcgov/ssdtools#111]
## r2 and RSS for model fits

It would be useful to be able to get more information on the strength of fitted models (e.g., for reporting in journal articles) such as r2 and RSS. Can this be retrieved from the model fit information?

**Comment by joethorley** [comment]
These values can't be calculate for species sensitivity distributions which simply describe the variation in data. Goodness of fit statistics that can be output using `ssd_gof()` should be used instead.
