### ISSUE TITLE
Failure with dev testthat

### ISSUE THREAD

**Issue by hadley** [bcgov/ssdtools#156]
In https://github.com/bcgov/ssdtools/blob/master/tests/testthat/test-fit.R#L66, the `class` argument should be a single string, so I think you want:

```R
  expect_error(ssd_fit_dist(boron_data[1:5, ]), "^`nrow[(]data[)]` must be greater than or equal to 6, not 5[.]$", "chk_error")
```

**Comment by joethorley** [comment]
@Hadley - thanks - fixed.
