### ISSUE TITLE
ssd_plot functionality in RShiny (HTML)

### ISSUE THREAD

**Issue by ScottCoffin** [bcgov/ssdtools#160]
## The Bug

When running RShiny on a web browser, ssd_plot does not display, and an error is present, however it displays properly when running the RShiny app from the RStudio application. 
Further, geom_ssd is not compatible with plotly (possibly a feature with that package).

## A Reprex

Please include a minimal reproducible example (AKA a reprex). 
If you've never heard of a [reprex](http://reprex.tidyverse.org/) before, start by reading <https://www.tidyverse.org/help/#reprex>.

```r
# insert reprex here
```

**Comment by joethorley** [comment]
@ScottCoffin - is this still an issue?

**Comment by ScottCoffin** [comment]
I was able to resolve this issue by implementing the ssd through ggplot() instead of calling the built-in ssd_plot() function with the package. Thank you!
