### ISSUE TITLE
Need <5 data fitting in SSD model

### ISSUE THREAD

**Issue by zhangjw7sustech** [bcgov/ssdtools#164]
Dear Author,
Hello!
I am a new user of R and try to fit SSD model using the ssdtools, which is really a user-friendly platform. However, in my own work, I need fit a SSD curve using <5 data (5 or 4), ssdtools shows an error as follows.
_Error: All distributions failed to fit.
In addition: Warning message:
Distribution lnorm failed to fit: Error : `nrow(data)` must be greater than or equal to 6, not 5._
Is it possible to fit a SSD curve using <5 data?
Thank you for your help!

**Comment by joethorley** [comment]
It's possible in principle but not recommended and therefore not permitted by ssdtools.
