### ISSUE TITLE
Add argument to allow passing a minimum samples argument to allow lower or higher values

### ISSUE THREAD

**Issue by beckyfisher** [bcgov/ssdtools#178]
Given that different jurisdictions have different minimum sample requirements for SSD's (for example, in Australia the current minimum is 5, although 8 or more is recommended), it would be useful if there were an argument to allow values other than the current 6 to be used. The default of this argument would remain at six to ensure the existing behaviour doesn't change.

**Comment by joethorley** [comment]
This is a great idea I'm thinking it could occur after dists in the arguments to `ssd_fit_dists()` and `ssd_fit_dist()` and be called something like min_samples = 6.

We should probably check its non-missing whole number using `chk_wnum()` and perhaps also chk that its range is between 5L and something like 12L (?) using `chk_range()`.

**Comment by joethorley** [comment]
done in tmbtools branch with nrow argument
