### ISSUE TITLE
Are we sure log-gumbel and inverse Weibull and are different distributions?

### ISSUE THREAD

**Issue by joethorley** [bcgov/ssdtools#209]

**Comment by cschwarz-stat-sfu-ca** [comment]
From https://hydrologie.org/hsj/470/hysj_47_01_0107.pdf
[image: Screen Shot 2021-07-26 at 18.31.55.png]

So the log(Concentration) follows a gumbel distribution. Just like a
log-normal, when the log(Concentration) follows a normal distribution.
The Concentration (in the original units) follows the pdf in (2) above.

For the inverse weibull, if Y ~ weibull, then 1/Y ~ Inverse weibull.
From
https://www-tandfonline-com.proxy.lib.sfu.ca/doi/full/10.1080/02664763.2020.1803815
the pdf of the inverse weibull is
[image: Screen Shot 2021-07-26 at 20.06.28.png]
so we need to compare the pdf of (2) in the first screenshot with the pdf
(1) in the second screen shot.

The inverse Weibull is also known as the Frechet distribution

And with a little work, you can show that these pdf are the same!

I've attached a little demonstration where I generated 1000 rv from
logGumbel and fit the logGumbel and invWeibull and get the exact same
estimates
with appropriate transformations and the same resulting pdf.. So we can
delete one of these and just leave a note.

Carl

**Comment by cschwarz-stat-sfu-ca** [comment]
Great, thanks Carl! Very helpful!

**Comment by joethorley** [comment]
Thanks Carl - I'm thinking we keep the log-Gumbel since this was in the previous version of ssdtools.

**Comment by joethorley** [comment]
removed invweibull on tmbtools.
