### ISSUE TITLE
invpareto appears to be misspecified

### ISSUE THREAD

**Issue by joethorley** [bcgov/ssdtools#210]
``` r
library(ssdtools)
hist(ssdtools:::rinvpareto(1000, 1, 1), breaks = 100)
```

![](https://i.imgur.com/iG6aAXa.png)

<sup>Created on 2021-07-10 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by cschwarz-stat-sfu-ca** [comment]
Not sure what you mean by mis-specified? Histogram is rough only because of small bin sizes? Maximum bound is at 1 as described by one of the parameters? Carl

**Comment by joethorley** [comment]
Good point - yes the random generation code appears to be functioning correctly

``` r
library(ssdtools)
hist(ssdtools:::rinvpareto(1000, 1, 2), breaks = 100)
```

![](https://i.imgur.com/z7nrPAT.png)

<sup>Created on 2021-07-15 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by joethorley** [comment]
``` r
library(ssdtools)
hist(ssdtools:::rinvpareto(1000, 10, 2), breaks = 100)
```

![](https://i.imgur.com/jkIZIuH.png)

<sup>Created on 2021-07-15 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by joethorley** [comment]
``` r
library(ssdtools)
hist(ssdtools:::rinvpareto(1000, 0.1, 2), breaks = 100)
```

![](https://i.imgur.com/KR6uDiY.png)

<sup>Created on 2021-07-15 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by joethorley** [comment]
implement in tmbtool branch
