### ISSUE TITLE
ssd_fit_dists crashing R

### ISSUE THREAD

**Issue by SantoClau** [bcgov/ssdtools#212]
When I run the function "ssd_fit_dists", with the boron data, R crashes and will appear message on the console:

"$start.arg
$start.arg$locationlog
[1] 2.561645

$start.arg$scalelog
[1] 2.293228

$fix.arg
NULL"

**Comment by joethorley** [comment]
Can you provide a reproducible example https://www.tidyverse.org/help/

**Comment by SantoClau** [comment]
Hello! I was having problems with the function that allowed me to provide that example, ended up having to update all of the packages that I had, which in turn solved my initial problem. Thank you for your help!
