### ISSUE TITLE
Undoing future::plan() thinko

### ISSUE THREAD

**Issue by HenrikBengtsson** [bcgov/ssdtools#256]
Hi, I spotted:

https://github.com/bcgov/ssdtools/blob/297dfa8adcd0202cd5535f7ec7f64be9459179d4/R/test-helpers.R#L17

That reset the plan to `sequential`, but note that the user might have had another plan set.  Instead, it's better to do something like what `?future::plan` suggests:

```r
oplan <- plan(new_set_of_strategies)
on.exit(plan(oplan), add = TRUE)
```

PS. I'm glad that you're also undoing `registerDoFuture()`

**Comment by joethorley** [comment]
Thanks @HenrikBengtsson - Good spot. We are putting out a new patch in 10 days. We'll fix for that.
