### ISSUE TITLE
Compilation fails: error: Eigen/Dense: No such file or directory

### ISSUE THREAD

**Issue by Enchufa2** [bcgov/ssdtools#272]
TMB is LinkingTo RcppEigen, but it does not require it as Depends or Imports, which means that compilation of ssdtools fails in systems with precompiled TMB, where RcppEigen is not necessarily installed. Given that ssdtools uses Eigen, please add RcppEigen to LinkingTo.

**Comment by joethorley** [comment]
done thanks!
