### ISSUE TITLE
Fitting Gompertz distribution

### ISSUE THREAD

**Issue by yuichiwsk** [bcgov/ssdtools#279]
I am curious as to why fitting of the Gompertz distribution often fails, even when the data is generated from this distribution.

Here is an example:

set.seed(10)
data1 <- data.frame(Conc = ssd_rgompertz(30, 0.02, 0.0002))
fit1 <- ssdtools::ssd_fit_dists(data1, dists = c('gompertz')) # OK

set.seed(11)
data2 <- data.frame(Conc = ssd_rgompertz(30, 0.02, 0.0002))
fit2 <- ssdtools::ssd_fit_dists(data2, dists = c('gompertz')) # Not ok

set.seed(12)
data3 <- data.frame(Conc = ssd_rgompertz(30, 0.02, 0.0002))
fit3 <- ssdtools::ssd_fit_dists(data3, dists = c('gompertz')) # Not ok

Many thanks in advance, Yuichi

**Comment by joethorley** [comment]
Hi @yuichiwsk - It's at least partly due to the fact that its challenging to get reasonable initial starting values.

See issue https://github.com/bcgov/ssdtools/issues/223

**Comment by joethorley** [comment]
This is a reason its not one of distributions recommended by British Columbia, Canada, Australia or New Zealand.

> ssd_dists_bcanz()
[1] "gamma"       "lgumbel"     "llogis"      "lnorm"       "lnorm_lnorm" "weibull"

**Comment by joethorley** [comment]
I've filed an issue to add an FAQ on this.

https://github.com/bcgov/ssdtools/issues/281

**Comment by yuichiwsk** [comment]
Thank you very much for your swift reply, @joethorley!
