### ISSUE TITLE
Shinyssdtools doesn’t calculate 95% CLs for lognorm-lognorm

### ISSUE THREAD

**Issue by beckyfisher** [bcgov/ssdtools#295]
Feedback from CSIRO researchers in Australia has been that they have been unable to use the currently recommended distribution set because the lnorm-lnorm mixture distribution fails to return confidence intervals. This happens, for example using the boron dataset and is presumably related to the strict default criterion for pboot, which for the boron dataset is 0.98. Given fitdistplus and burrlioz never assessed pboot, I recommend this criterion should be relaxed.

**Comment by joethorley** [comment]
@beckyfisher - any suggestions on what it should be relaxed to?

**Comment by beckyfisher** [comment]
Hi Joe, what was the basis for the original selection of 0.99? Do you have some references for that? We'd probably need to do a more thorough literature search, but off the top of my head 0.8 might seem reasonable. A much better strategy, however, would be to use a while loop or some such to continue to bootstrapping until you have the intended number of samples.

**Comment by joethorley** [comment]
Actually thinking about it for a second longer we don't even need Bayesian analysis if we simulate data using known parameters.

**Comment by joethorley** [comment]
This was to with instability in lnorm-lnorm in bootstrap sample. Largely fixed with min_pmix = 3/n.
