### ISSUE TITLE
ssd is crashing when 'group by symbol' is selected

### ISSUE THREAD

**Issue by atillmanns** [bcgov/ssdtools#303]
The app is crashing when symbol by group is selected on the predicted tab.

**Comment by joethorley** [comment]
@atillmanns - thanks Angeline - we'll look into it in the next week

**Comment by joethorley** [comment]
@sebdalgarno - can you take a look at this with the cran version of ssdtools?

**Comment by sebdalgarno** [comment]
yes I can - note this will be a bug in the shiny app

**Comment by joethorley** [comment]
Right - can you file an issue and deal with it there.

**Comment by sebdalgarno** [comment]
moved to issue in shinyssdtools - https://github.com/bcgov/shinyssdtools/issues/124

**Comment by sebdalgarno** [comment]
@atillmanns please close this issue once you've redeployed the app and confirmed that the bug is fixed

**Comment by joethorley** [comment]
Fixed https://github.com/bcgov/shinyssdtools/issues/124
