### ISSUE TITLE
Unable to plot 

### ISSUE THREAD

**Issue by mctavishk** [bcgov/ssdtools#33]
Keep getting this error when trying to plot:

"Error in is.finite(x) : 
  default method not implemented for type 'language'" 

This happens when using the script straight from the Shiny App using Boron as the example as well as when I use my own data.
Any suggestions?

**Comment by joethorley** [comment]
@mctavishk - ah yes we need to update the shiny app based on the changes I recently made to ssdtools - we'll make this a priority. If the meantime if you send me the problem script I'll fix it for you.

**Comment by joethorley** [comment]
@mctavishk - we'll fix it tomorrow

**Comment by joethorley** [comment]
@mctavishk I was unable to replicate your issue with the most recent version of ssdtools. Can you update your packages and if the error still occurs post the full output so I can see where the problem is ?

**Comment by mctavishk** [comment]
Installing most recent version did the trick! How often should I be updating ssdtools? Thx

**Comment by joethorley** [comment]
As a general rules I update all my packages whenever I get an error I don't understand to see if this fixes. Without errors I update all my packages about once a week.
