### ISSUE TITLE
gompertz not fitting

### ISSUE THREAD

**Issue by JenniGadd** [bcgov/ssdtools#34]
hi there, when i try to fit my data set using the R code, it works but i get errors when i attempt to plot, or make predictions. I've attached the data set. [Cu_lowdata.xlsx](https://github.com/bcgov/ssdtools/files/2688639/Cu_lowdata.xlsx)

This is the code and errors:
> Cu_low_dists <- ssd_fit_dists(LowerCuMarData)
> autoplot(Cu_low_dists)
Error in pgompertz(q = c(0.7, 1.3, 1.94), shape = 0.391386784692936, scale = 0.313425202466778) : 
  unused argument (q = c(0.7, 1.3, 1.94))
> ssd_gof(Cu_low_dists)
Error in pgompertz(q = c(0.7, 1.3, 1.94), shape = 0.391386784692936, scale = 0.313425202466778) : 
  unused argument (q = c(0.7, 1.3, 1.94))

It works when i do it in the R shiny app. 

Is there a way to exclude some fits when using the R code, as you can in the Shiny app?
Thanks,
Jenni

**Comment by JenniGadd** [comment]
Just upgraded to new R version and new ggplot2 version and seems to work now!

**Comment by joethorley** [comment]
@JenniGadd I'm glad updating fixed it
