### ISSUE TITLE
llog initial values need adjusting when small values

### ISSUE THREAD

**Issue by joethorley** [bcgov/ssdtools#36]
consider

```
  data <- ssdtools::boron_data
  data$Conc <- data$Conc / 100
  ssdtools:::ssd_fit_dist(data, dist = "llog")
```

**Comment by cschwarz-stat-sfu-ca** [comment]
Problem is that the FAdist::dllog() -> dlogis()  "REVERSES" the means of scale and shape. Documentation is very unclear but look at underlying distribution code:

> FAdist::dllog
function (x, shape = 1, scale = 1, log = FALSE) 
{
    fx <- dlogis(log(x), location = scale, scale = shape, log = FALSE)/x
    if (log) 
        return(log(fx))
    else return(fx)
}

So scale parameter -> location on log() scale; and shape parameter -> scale (sd) on log() scale.'

But the initial values have:
...
  } else if (dist$distr == "llog") {
    dist$start <- list(shape = mean(log(x)), 
                       scale = pi * stats::sd(log(x)) / sqrt(3))

... which is "reversed' from what was expected.

Solution is to change the initial values:
    dist$start <- list(scale = mean(log(x)), 
                                shape = pi * stats::sd(log(x)) / sqrt(3))


Now dividing the data by 1000 has no impact on the fit other than change the location by log(1000) as expected.
