### ISSUE TITLE
Feature request: export `expect_snapshot_data()`?

### ISSUE THREAD

**Issue by d-morrison** [bcgov/ssdtools#379]
Hi, I just stumbled on your `expect_snapshot_data()` function; it would be great to able to call this function easily, and not automatically skip on windows. I'm going to fork and edit for now, but wanted to thank you for writing it and encourage you to keep developing it! Very helpful, and I haven't found the same functionality anywhere else.

**Comment by d-morrison** [comment]
PS - looks like your main branch already removed the `skip_()`s, so I'll just use that with `:::` for now!

**Comment by joethorley** [comment]
Hi @d-morrison - I'm glad you find it helpful. Feel free to just copy and paste into your own packages (I'd rather not export and have to maintain plus ssdtools is super dependency heavy so no-one is going to want to install it unless they are doing species sensitivity distribution modeling - so I'm going to close this issue and your PR but I appreciate the interest and message.

**Comment by d-morrison** [comment]
Fair enough! Will do.

**Comment by d-morrison** [comment]
> Hi [@d-morrison](https://github.com/d-morrison) - Very cool. This is ok with me and there is no need to add me as a co-author. Have fun!

thanks! will do

**Comment by joethorley** [comment]
@d-morrison - congrats!
