### ISSUE TITLE
Some equations not rendering properly on github pages

### ISSUE THREAD

**Issue by beckyfisher** [bcgov/ssdtools#387]
Some equations not rendering properly on github website
![image](https://github.com/user-attachments/assets/0dff94eb-3269-452c-8b6b-5541d7b8749e)

**Comment by joethorley** [comment]
done

**Comment by flor14** [comment]
@joethorley  I'm reviewing the documentation, and it seems there are still issues with some images and formulas. I'm checking the webpage linked to the repository: https://bcgov.github.io/ssdtools/
Is this the correct link?

![Image](https://github.com/user-attachments/assets/4f8dc0d1-fcc0-4a95-b644-1a29d4b15494)
![Image](https://github.com/user-attachments/assets/a2b8fd70-acbd-43aa-9cc6-55667eff5d9c)

**Comment by joethorley** [comment]
@flor14  - sorry I should have specified you need to look at https://bcgov.github.io/ssdtools/dev/

The main website will update once we release the current version.
