### ISSUE TITLE
llogis, gompertz and weibull SSD parameters appear to extract incorrectly

### ISSUE THREAD

**Issue by CathNeelamraju** [bcgov/ssdtools#390]
# libraries------------
   library(ssdtools)
#> Warning: package 'ssdtools' was built under R version 4.2.3
#> Warning in checkMatrixPackageVersion(): Package version inconsistency detected.
#> TMB was built with Matrix version 1.6.1
#> Current Matrix version is 1.5.1
#> Please re-install 'TMB' from source using install.packages('TMB', type = 'source') or ask CRAN for a binary version of 'TMB' matching CRAN's 'Matrix' package
#> Please replace the following in your scripts:
#> - `ssdtools::boron_data` with `ssddata::ccme_boron`
#> - `ssdtools::ccme_data` with `ssddata::ccme_data`
   library(openxlsx)
#> Warning: package 'openxlsx' was built under R version 4.2.3
   library(tidyverse)
#> Warning: package 'tidyverse' was built under R version 4.2.3
#> Warning: package 'ggplot2' was built under R version 4.2.3
#> Warning: package 'tibble' was built under R version 4.2.3
#> Warning: package 'tidyr' was built under R version 4.2.3
#> Warning: package 'purrr' was built under R version 4.2.3
#> Warning: package 'dplyr' was built under R version 4.2.3
#> Warning: package 'lubridate' was built under R version 4.2.3
   library(ggplot2)
   library(ggpubr)
#> Warning: package 'ggpubr' was built under R version 4.2.3
   
   # Methomyl----------
   setwd("C:/Users/uqcneela/OneDrive - The University of Queensland/General - Sci SEES Res Reef Catchment Science Partnership/Project 3/Catherine Neelamraju/PRM build")
   # Read in data
   Methomyl <- read.csv("Example_methomyl.csv")
   
   # check formats
   str(Methomyl)
#> 'data.frame':    34 obs. of  16 variables:
#>  $ Media                           : chr  "Fresh" "Fresh" "Fresh" "Fresh" ...
#>  $ Media.Type                      : chr  "Fresh water" "Fresh water" "Surface or ground, reconstituted or dechlorinated tap water" "Fresh water" ...
#>  $ Organism.Type                   : chr  "Crustacean" "Insect" "Insect" "Insect" ...
#>  $ Species.Scientific.Name         : chr  "Ceriodaphnia reticulata" "Cheumatopsyche brevilineata" "Chimarra atterima" "Chironomus plumosus" ...
#>  $ Phylum                          : chr  "Arthropoda" "Arthropoda" "Arthropoda" "Arthropoda" ...
#>  $ Class                           : chr  "Branchiopoda" "Insecta" "Insecta" "Insecta" ...
#>  $ Hetero.Phototroph               : chr  "Heterotroph" "Heterotroph" "Heterotroph" "Heterotroph" ...
#>  $ Preferential.Selection.Groupings: int  4 4 4 4 4 4 4 4 4 1 ...
#>  $ Conc                            : num  0.211 6.81 2590 68.999 0.71 ...
#>  $ Exposure.duration.days.         : int  2 2 2 2 2 1 4 2 4 21 ...
#>  $ Data.type                       : chr  "Acute EC50" "Acute EC50" "Acute LC50" "Acute LC50" ...
#>  $ Endpoint                        : chr  "Intoxication" "Intoxication" "Mortality" "Intoxication" ...
#>  $ Measure                         : chr  "Immobile" "Immobile" "" "Immobile" ...
#>  $ Reference                       : chr  "Mano et al (2010)" "Yokoyama et al (2009)" "OPP" "OPP, Mayer & Ellersieck (1986)" ...
#>  $ Notes                           : chr  "" "" "check ref" "Geomean, check ref" ...
#>  $ Group                           : chr  "Arthropod" "Arthropod" "Arthropod" "Arthropod" ...
   
   # > SSD fit-----------
   # FIT 4 -> Final model fit for Methomyl
   fit4_Methomyl <- ssd_fit_dists(Methomyl, dists = c("llogis")) 
   
   # # examine plot - Fit 4
   Methomyl_fit4plot <- ssd_plot_cdf(fit4_Methomyl)
   
   # Fit 4 predict
   fit4_Methomyl_pred <- predict(fit4_Methomyl, min_pboot=0.99, ci = TRUE)
   
   # find PC values for Fit 4
   ssd_hc(fit4_Methomyl, percent = 1, nboot = 10000) # PC99
#> # A tibble: 1 × 10
#>   dist    percent    est    se   lcl   ucl    wt method     nboot pboot
#>   <chr>     <dbl>  <dbl> <dbl> <dbl> <dbl> <dbl> <chr>      <int> <dbl>
#> 1 average       1 0.0358    NA    NA    NA     1 parametric     0    NA
   ssd_hc(fit4_Methomyl, nboot = 10000) # PC95 (note: 5 % is the standard setting, no need to specify)
#> # A tibble: 1 × 10
#>   dist    percent   est    se   lcl   ucl    wt method     nboot pboot
#>   <chr>     <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <chr>      <int> <dbl>
#> 1 average       5 0.260    NA    NA    NA     1 parametric     0    NA
   ssd_hc(fit4_Methomyl, percent = 10, nboot = 10000) # PC90
#> # A tibble: 1 × 10
#>   dist    percent   est    se   lcl   ucl    wt method     nboot pboot
#>   <chr>     <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <chr>      <int> <dbl>
#> 1 average      10 0.637    NA    NA    NA     1 parametric     0    NA
   ssd_hc(fit4_Methomyl, percent = 20, nboot = 10000) # PC80
#> # A tibble: 1 × 10
#>   dist    percent   est    se   lcl   ucl    wt method     nboot pboot
#>   <chr>     <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <chr>      <int> <dbl>
#> 1 average      20  1.68    NA    NA    NA     1 parametric     0    NA
   
   
   # > backfit check----------
   # these all validate correctly
   ssd_hp(fit4_Methomyl, conc = 0.0358 ) # back-calculate using PC99
#> # A tibble: 1 × 10
#>   dist      conc   est    se   lcl   ucl    wt method     nboot pboot
#>   <chr>    <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <chr>      <int> <dbl>
#> 1 average 0.0358  1.00    NA    NA    NA     1 parametric     0    NA
   ssd_hp(fit4_Methomyl, conc = 0.260 ) # back-calculate using PC95
#> # A tibble: 1 × 10
#>   dist     conc   est    se   lcl   ucl    wt method     nboot pboot
#>   <chr>   <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <chr>      <int> <dbl>
#> 1 average  0.26  5.01    NA    NA    NA     1 parametric     0    NA
   ssd_hp(fit4_Methomyl, conc = 0.637 ) # back-calculate using PC90
#> # A tibble: 1 × 10
#>   dist     conc   est    se   lcl   ucl    wt method     nboot pboot
#>   <chr>   <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <chr>      <int> <dbl>
#> 1 average 0.637  10.0    NA    NA    NA     1 parametric     0    NA
   ssd_hp(fit4_Methomyl, conc = 1.68 ) # back-calculate using PC80
#> # A tibble: 1 × 10
#>   dist     conc   est    se   lcl   ucl    wt method     nboot pboot
#>   <chr>   <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <chr>      <int> <dbl>
#> 1 average  1.68  20.0    NA    NA    NA     1 parametric     0    NA
   
   # > extract SSD params
   fit4_Methomyl$llogis
#> Distribution 'llogis'
#>   locationlog 2.18565
#>   scalelog 1.20031
   
   # > plot using SSD params
   Methomyl_plotcheck <- ssd_plot_cdf(list(llogis = c(locationlog = 2.18565, scalelog = 1.20031)))
   
   # combine plots and compare
   # these appear to be the same
   FitComp <- ggarrange(Methomyl_fit4plot, Methomyl_plotcheck, ncol = 2, nrow = 1)
   FitComp

   
   # However, when using the SSD params to calculate PAF using a log logistic function the numbers appear incorrect
   # this should give a result of 20% PAF but instead it is 67.6 which is not correct
   location <- 2.18565
   scale <- 1.20031
   x <- 1/(1+'^'((1.68/scale), (-1*location)))*100
   x
#> [1] 67.58678
   
   # > comparison with other published values------
   # see Tebuthiuron SSD in attached D of report here:
   # https://www.publications.qld.gov.au/ckan-publications-attachments-prod/resources/c65858f9-d7ba-4aef-aa4f-e148f950220f/pesticide-risk-baseline-project-report.pdf?ETag=a9665f53d62acabcddcc9fbe38e025b5
   # note this SSD was generated using Burrlioz in 2018
   
   # PC values from report
   Teb_PC99 <- 4.7
   Teb_PC95 <- 11
   Teb_PC90 <- 17
   Teb_PC80 <- 26
   
   # SSD params from report
   # note SSD params need to be back-transformed using exp()
   # the formula appears to be fine --> calculates correctly for log logistic
   location <- exp(0.64284)
   scale <- exp(3.97322)
   x <- 1/(1+'^'((Teb_PC80/scale), (-1*location)))*100
   x
#> [1] 20.42281
   
   # problem statement: --------
   # Methomyl Fit 4 PC values are reasonable given the input data
   # SSD plot using SSD params looks the same as that generated using ssd_plot_cdf() function
   # ssd_hp() back-calculates correctly
   # my log logistic function appears to calculate PAF correctly using Tebuthiuron parameters extracted from Burrlioz in 2018
   # However, i getting the wrong numbers using the Methomyl llogis SSD params exported from ssdtools --> why?
Created on 2024-12-02 with [reprex v2.1.1](https://reprex.tidyverse.org/)[Example_methomyl.csv](https://github.com/user-attachments/files/17971060/Example_methomyl.csv)
# i am having the same problem with gompertz and weibull (happy to send through example data files if needed)

**Comment by joethorley** [comment]
@CathNeelamraju I didn't have time to dig into the formulation you used for the log-logistic but did put together the following reprex demonstrating that the implementation of the log-logistic for ssdtools is consistent with R.

``` r
library(ssdtools)

p <- 0.05
locationlog <- 2.18565
scalelog = 1.20031

ssd_plot_cdf(list(llogis = c(locationlog = locationlog, scalelog = scalelog)))
```

![](https://i.imgur.com/puUiLCN.png)

``` r

ssd_qllogis(p, locationlog = locationlog, scalelog = scalelog)
#> [1] 0.2596062

exp(stats::qlogis(p, location = locationlog, scale = scalelog))
#> [1] 0.2596062

1 - 1/(1 + exp((log(0.2596062) - locationlog) / scalelog))
#> [1] 0.05000001
```

<sup>Created on 2024-12-02 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>
