### ISSUE TITLE
Correction to initial values for gamma distribution

### ISSUE THREAD

**Issue by cschwarz-stat-sfu-ca** [bcgov/ssdtools#57]
Gamma distribution with shape (a) and scale (s) has
"mean and variance are E(X) = a*s and Var(X) = a*s^2" according to the help file for dgamma.

Solving for $a$ and $s$ gives
   $ a = V(x) / E[x]$
so using method of moments, use a starting value for $a = var(x) / mean(x)$.

Solving for $a$ then gives
   $  a = E[X] / s$
and a moment estimator is then $a = mean(x) / s = mean(x) / (V(x)/Mean(x) = mean^2/V(x)$

We have
if (dist$dist == "gamma") {
    dist$start <- list(
      scale = stats::var(x) / mean(x),
      shape = mean(x)^2 / stats::var(x)^2
    )
so it appear we have and extra square in the last line. This should read

  if (dist$dist == "gamma") {
    dist$start <- list(
      scale = stats::var(x) / mean(x),
      shape = mean(x)^2 / stats::var(x)
    )
 
i.e. remove the ^2 from the var(x) in the initial value for shape.

Fortunately, the fitdist() function appears to be robust to making the shape parameter too small so no obvious user impact.

**Comment by joethorley** [comment]
done
