### ISSUE TITLE
Gamma distribution reports NA for standard error estimate; warn user; solution is rescale data

### ISSUE THREAD

**Issue by cschwarz-stat-sfu-ca** [bcgov/ssdtools#58]
For some extreme sets of data, the gamma distribution reports NA for the standard error. Eg.]

library(ssdtools)
test.csv <- textConnection(
"dummy  ,  Conc  ,  Units 
        all  ,  0.1  ,    ug/L    
        all  ,  0.12  ,  ug/L    
        all  ,  0.24  ,  ug/L    
        all  ,  0.42  ,  ug/L   
        all  ,  0.67  ,  ug/L    
        all  ,  0.78  ,  ug/L    
        all  ,  120  ,  ug/L    
        all  ,  2030  ,  ug/L    
        all  ,  9033  ,  ug/L    
        all  ,  15000  ,  ug/L   
        all  ,  15779  ,  ug/L    
        all  ,  20000  ,  ug/L    
        all  ,  31000  ,  ug/L    
        all  ,  40000  ,  ug/L   
        all  ,  105650  ,  ug/L")
test <- read.csv(test.csv, header=TRUE, strip.white=TRUE, as.is=TRUE)

ssd_fit_dists(test, dists="gamma")

reports

Fitting of the distribution ' gamma ' by maximum likelihood 
Parameters:
          estimate Std. Error
scale 9.695693e+04        NaN
shape 1.642224e-01 0.04142257

Estimates of scale and shape are ok, but it was unable to compute a standard error for the scale parameter. This appears to be a scaling problem in inverting the hessian. The standard error for the scale parameter is about 67000 and the se for the shape is .04. So the vcov will have terms on the order of 67000^2 and .04^2 which vary by 2.8 x 10^12 (!) so I suspect that it is a numerical issue

If you rescale the data

factor=100
test2 <- test
test2$Conc <- test2$Conc/ factor
ssd_fit_dists(test2, dists="gamma")

all is well
Fitting of the distribution ' gamma ' by maximum likelihood 
Parameters:
         estimate  Std. Error
scale 969.5359604 674.2705097
shape   0.1641717   0.0454135

The pdf for the gamma has a term x/s so if you multiple x by a factor k and multiply s by a factor of k, the pdf is unchanged except for the change in the scale factor.

I would advise user if any estimates have NA for the standard errors and advise them that a rescaling may be appropriate. We could make a specific message for each distribution, i.e. typically advise gamma users to divide by a factor k, or a generic message and the user needs to try both multiplying or dividing the data by a factor until message "disappears".

Estimates are ok, so estimates of HCx are ok. Bootstrapping used to compute SE for HCx so this should also work fine. 

Carl

**Comment by joethorley** [comment]
done
