### ISSUE TITLE
burrIII2 and llogis are identical

### ISSUE THREAD

**Issue by joethorley** [bcgov/ssdtools#89]
drop burrIII2 and replace in default set with llogis?

rename burrII3 to just burrII?

**Comment by joethorley** [comment]
@atillmanns - what do you want to do about this?

The options are

- Drop burrIII2 from default set and have just lnorm and gamma as defaults or
- Replace burrrIII2 with llogis in default set.

Whichever we choose we should rename burrIII3 to burrIII in my opinion. Thought?

**Comment by joethorley** [comment]
I think we should replace burrrIII2 with logis in the default set as this requires the minimum number of changes.

**Comment by atillmanns** [comment]
Agreed.  So three default distributions - gamma, lnorm, llogis.  We'll have to remember to update the article on distribution selection

**Comment by joethorley** [comment]
On reflection I think we should drop llogis as so similar to lnorm and primarily included for historical reasons. Some sort-term pain but better in the long-run.

**Comment by joethorley** [comment]
Decided to stick with llogis and perform analysis of lots of datasets to see how similar/disimilar different distributions are to select the default set.
