### ISSUE TITLE
predict no longer generates confidence intervals

### ISSUE THREAD

**Issue by joethorley** [bcgov/ssdtools#91]
With the new version (0.1.0), the confidence interval of the whole curve did not result when applying the “predict” to the average product of “ssd_fit_dists”

```r
Percent est se lcl ucl dist  
   <int> <dbl> <dbl> <dbl> <dbl> <chr> 
 1 1 0.304 NA NA NA average
 2 2 0.544 NA NA NA average
 3 3 0.780 NA NA NA average
 4 4 1.01 NA NA NA average
 5 5 1.25 NA NA NA average
 6 6 1.49 NA NA NA average
```

**Comment by joethorley** [comment]
This is because in version 0.1.0 the default value of the `ci` argument changed from `TRUE` to `FALSE`.

The solution is to set `ci = TRUE`

```r
pred <- predict(dist, ci = TRUE, nboot = 10000L)
```

**Comment by sreynaldi** [comment]
> pred <- predict(dist, ci = TRUE, nboot = 100L)
### Error in rlogis(n = n, location = exp(lscale), scale = exp(lshape)) : 
  invalid arguments

**Comment by twinstan1988** [comment]
Hi, 
I still have the following error after adding ci = TRUE

Error in rlogis(n = n, location = exp(lscale), scale = exp(lshape)) : 
  invalid arguments

**Comment by joethorley** [comment]
See issue #96

**Comment by twinstan1988** [comment]
> See issue #96

Thank you!!
